# fly.toml app configuration file generated for jobjigsaw on 2023-11-04T00:34:18+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jobjigsaw"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
