name: Fly Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/fly.yml'


jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Create Main resume
        run: |
          echo "${{ secrets.MAIN_RESUME }}" | base64 -d > ./mainResume.json
      - uses: superfly/flyctl-actions/setup-flyctl@master
        run: flyctl secrets set OPENAI_API_KEY=$(echo ${{ secrets.OPENAI_API_KEY }})
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}